# Generated by Django 5.2.14 on 2026-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='random@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
